### ISSUE TITLE
Helm Hook

### ISSUE THREAD

**Issue by Mingadinga** [Mingadinga/2023_Study_Helm#10]
# Helm Hook이란?

Hook이란?

- 차트 개발자가 릴리스 수명주기의 특정 지점에 개입하여
- 원하는 동작을 추가하는 기능

Hook의 사용 목적

- App의 기능을 보조하기 위한 용도
- 쿠버네티스 리소스 생성 시 우선순위 할당

# Helm

- `annotation : pre-install` : 메인 앱이 구동되기 전에 다른 서버의 헬스 체크나 데이터 백업이 필요한 경우, helm install 명령어를 사용하면 pre-install 애노테이션을 붙인 파드를 먼저 배포한다.
- `annotation : pre-upgrade` : helm upgrade 명령어를 사용하면 pre-upgrade 애노테이션을 붙인 파일을 먼저 배포한다.
- 그외에도 rollback, uninstall 명령어 전에 동작하는 `pre-rollback`, `pre-delete` 옵션이 있다.
- 후처리가 필요하다면 `post-install`, `post-upgrade`, `post-rollback`, `post-delete` 옵션을 활용한다.
- `annotation : test` : helm test 명령어를 사용하면 test 애노테이션이 붙은 파드가 실행된다.
- 쿠버네티스 사용자 정의 리소스를 담는 `crds`에 pre-install 애노테이션을 붙이면 pre-pod보다 먼저 실행된다.

# ****Helm Hook 기본 Flow****

파드에 다음과 같은 애노테이션이 붙어있다고 가정하자.

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/70d814ef-1cf4-4831-8b77-f857ad2bdffb)

- helm install : deployment.yaml 배포
- helm upgrade : crd-prod.yaml 성공 → pre-pod.yaml 성공 → deployment.yaml 실행(running 기다리려면 wait 옵션) → test-pod.yaml 성공
- helm test : test-pod.yaml 실행

# ****Helm Hook 속성****

- `hook-weight` : 배포 순서 지정. 값이 작을수록 빨리 생성됨. 실행 우선 순위는 음수 → 0 → 양수. 기본값은 0이다.
- `hook-delete-policy` : Hook으로 만든 리소스에 대한 삭제 시점을 정함. helm upgrade 명령어 사용시 일어남.
    - `before-hook-creation` : 기존에 Hook 리소스가 존재한다면 삭제하고 실행
    - hook-succedded : 훅이 정상으로 끝나면 Hook 리소스 삭제
    - hook-failed : 훅이 실패로 끝나면 Hook 리소스 삭제
- `resource-policy : keep` : helm uninstall 하더라도 Hook Pod는 삭제되지 않는다. 추후에 Hook에 대한 gc 추가 예정. 삭제하면 안되는 Hook 리소스에 keep 처리한다.

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/b8914937-1613-4b35-90f4-410925906405)

# ****Helm Hook 기본 Flow**** 실습

## 리소스 준비

```bash
helm create mychart-hook
rm -rf deployment.yaml  hpa.yaml  ingress.yaml  service.yaml  serviceaccount.yaml  tests/test-connection.yaml
```

vi pre-pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pre-pod
  annotations:
    helm.sh/hook: pre-upgrade
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

vi deployment.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    type: app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      type: app
  replicas: 1
  template:
    metadata:
      labels:
        type: app
      annotations:
        rollme: {{ randAlphaNum 5 | quote }} # 자동 재배포
    spec:
      initContainers:
      - name: init-myservice
        image: kubetm/app
        command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
      containers:
      - name: container
        image: kubetm/app
```

vi post-pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: post-pod
  annotations:
    helm.sh/hook: post-upgrade
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

mkdir tests && cd tests

vi test-pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    helm.sh/hook: test
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; curl svc/hostname; echo 'done'"]
```

mkdir crds && cd crds

vi crd-pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: crd-pod
  annotations:
    helm.sh/hook: pre-upgrade
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

## install

hook 파드 없이 deployment.yaml만 실행

```bash
cd templates
helm upgrade mychart-hook ./../ -n nm-1 --create-namespace --install
kubectl get pods -n nm-1

NAME                          READY   STATUS    RESTARTS   AGE
deployment-587b584487-qsz57   1/1     Running   0          37s
```

## upgrade

```bash
helm upgrade mychart-hook ./../ -n nm-1 --create-namespace --install
kubectl get pods -n nm-1

NAME                          READY   STATUS        RESTARTS   AGE
crd-pod                       0/1     Completed     0          67s
deployment-587b584487-qsz57   1/1     Terminating   0          3m4s
deployment-c5df69fd6-mhbc9    1/1     Running       0          27s
post-pod                      0/1     Completed     0          26s
pre-pod                       0/1     Completed     0          42s
```

기동 순서 : 이전에 설치했던 디플로이먼트는 종료, crd-pod → pre-pod → new deployment → post-pod

## test

```bash
helm test mychart-hook -n nm-1
kubectl get pods -n nm-1

NAME                         READY   STATUS      RESTARTS   AGE
deployment-c5df69fd6-mhbc9   1/1     Running     0          5m15s
post-pod                     0/1     Completed   0          5m14s
pre-pod                      0/1     Completed   0          5m30s
test-pod                     0/1     Completed   0          106s
```

# Hook Weight 실습

파드 1, 2, 3 순서대로 실행되어야 한다.

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/7deebd60-c85b-4641-a79d-80e0c9ada853)

```bash
helm create mychart-hook-weight
rm -rf deployment.yaml  hpa.yaml  ingress.yaml  service.yaml  serviceaccount.yaml  tests
```

vi pre-pod1.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pre-pod1
  annotations:
    helm.sh/hook: pre-install
    helm.sh/weight: "-1"
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

vi pre-pod2.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pre-pod2
  annotations:
    helm.sh/hook: pre-install
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

vi pre-pod3.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pre-pod3
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

vi deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      type: init
  replicas: 1
  template:
    metadata:
      labels:
        type: init
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: container
        image: kubetm/init
```

helm install 실행

```bash
helm upgrade mychart-hook-weight ./../ -n nm-2 --create-namespace --install
kubectl get pods -n nm-2

# 실행 순서 : pod1 -> pod2 -> pod3
NAME                         READY   STATUS      RESTARTS   AGE
deployment-95bb7b56d-lrvvs   1/1     Running     0          8s
pre-pod1                     0/1     Completed   0          53s
pre-pod2                     0/1     Completed   0          38s
pre-pod3                     0/1     Completed   0          23s
```

# Hook Delete Policy 실습

이전 실습 리소스 제거

```bash
rm -rf pre-pod2.yaml pre-pod3.yaml
kubectl delete pods -n nm-2 pre-pod2 pre-pod3
kubectl get pods -n nm-2
```

pod1을 *`hook-succeeded`*로 변경

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pre-pod1
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
#   helm.sh/hook-delete-policy: hook-failed
#   helm.sh/hook-delete-policy: before-hook-creation
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: kubetm/init
    command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
```

upgrade를 실행하면 hook-succeeded 모드로 실행되어 기존 리소스와 이름 충돌 발생. 지금까지는 before-hook-creation 모드로 실행되어 pre-pod1 배포가 성공하자마자 바로 삭제되었음.

```bash
helm upgrade mychart-hook-weight ./../ -n nm-2 --create-namespace --install

Error: UPGRADE FAILED: pre-upgrade hooks failed: warning: Hook pre-upgrade mychart-hook-weight/templates/pre-pod1.yaml failed: pods "pre-pod1" already exists
```

pre-pod1 삭제 후 다시 upgrade

```bash
kubectl delete pods -n nm-2 pre-pod1
helm upgrade mychart-hook-weight ./../ -n nm-2 --create-namespace --install
kubectl get pods -n nm-2

# pre-pod1은 삭제되고 없음
NAME                          READY   STATUS        RESTARTS   AGE
deployment-6bdb769db8-tc7q7   1/1     Running       0          5s
deployment-95bb7b56d-lrvvs    1/1     Terminating   0          10m
```
