### ISSUE TITLE
내 차트 만들기2

### ISSUE THREAD

**Issue by Mingadinga** [Mingadinga/2023_Study_Helm#6]
차트 템플릿을 만들 때 사용되는 함수와 파이프라인, 제어 흐름, 여러가지 함수들, 지역변수 관련 내용을 학습하자. 최종 차트가 어떻게 생성되는지 이해하는 것이 목표이다.

# 함수와 파이프라인

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/044bcddd-3e70-4d03-8bef-8616bbf131d3)

- 함수 사용 템플릿 : {{ 함수이름 인자* }}
- 내장 함수
    - quote 인자 : “인자”를 반환
    - include “사용자정의변수” 스코프 : 스코프에서 사용자 정의 변수를 찾아 임포트
- 파이프라인 : 함수 사용 가독성 향상을 위해 사용

# 흐름 제어

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/0b71b2eb-6720-4062-aac2-98162b62106d)

조건문

```yaml
{{- if eq .Values.dev.env "dev" }}
	log: debug
{{- else if .Values.dev.env }}
	log: {{ .Values.dev.log }}
{{- else }}
	log: error
{{- end }}
```

- 조건식 : 함수 매개변수* | 값 자체
- 조건 함수 : and, or, ne, not, eq, ge, gt, le, lt, default, empty
- 값 자체를 넘겼을 때 false로 판단하는 값 : Number 0, String “”, List [], Object {}, Boolean false, Null

범위

```yaml
{{- with .Values.dev }}
	env: {{ .env }} # .Values.dev.env
	log: {{ .log }} # .Values.dev.log
{{- end }}
```

- 범위 지정
- 가독성 향상

반복

```yaml
range:
	{{- range .Values.list }}
	- {{ . }} 
	{{- end }}
```

- 하위 요소에 꼭 - 적어야함! yaml 형식임
- {{ . }}에 파이프라인을 써서 함수 적용 가능

# 함수 종류

출력

- print “문자열”
- printf 포맷 매개변수*

```yaml
print: {{ print "Hard Coding" }}
printf: {{ printf "%s-%s" .Values.print.a .Values.print.b }}
```

삼항 연산자

- 변수 | ternary 값1 값2

```yaml
case1: {{ .Values.tenary.case1 | tenary "1" "2" }}
```

공백 맞춤

- indent 공백수 : 첫 줄부터 공백 채움
- nindent 공백수 : 첫 항목 엔터하고 첫 줄부터 공백 채움

```yaml
data:
	indent:
		{{- .Values.data | toYaml | nindent 4 }}
```

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/95f76926-2271-4051-9f1e-3f805a06b977)

default

- 값 | default “출력값” : 값이 true면 값을 찍고, false면 출력값을 찍는다
- 값 자체를 넘겼을 때 false로 판단하는 값 : Number 0, String “”, List [], Object {}, Boolean false, Null
- 출력값은 다양한 형태로 정의할 수 있다. 여기에 함수가 들어와도 된다
- list 매개변수* : 리스트를 만듦

```yaml
nil: {{ .Values.default.nil | default "default" }}
list: {{ .Values.default.boolean | default (list "default1" "default2") | toYaml | nindent 6 }}
object: {{ .Values.default.object | default "default: 1" | toYaml | nindent 6 }}
number: {{ .Values.default.number | default 1 }}
string: {{ .Values.default.string | default "default" }}
boolean: {{ .Values.default.boolean | default true }}
```
![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/c271e245-25a8-4aa0-80b5-3867e0598546)

공백 제거

- trimPrefix “Prefix” “Prefix포함문자열” : 앞에 붙은 Prefix 제거
- trimSuffix “Suffix” “Suffix포함문자열” : 뒤에 붙은 Suffix 제거
- trim “공백포함문자열” : 공백 제거

```yaml
trim: {{ trim "  hello " }}
trimPrefix: {{ trimPrefix "-" "-hello" }}
trimSuffix: {{ trimSuffix "-" "hello-" }}
```

랜덤

- randAlphaNum 자릿수 : 0-9a-zA-Z
- randAlpha 자릿수 : a-zA-Z
- randNumeric 자릿수 : 0-9
- randAscii 자릿수 : ASCII

```yaml
randAlphaNum: {{ randAlphaNum 5 }}
randAlpha: {{ randAlpha 5 }}
randNumeric: {{ randNumeric 5 }}
randAscii: {{ randAscii 5 }}
```

그외

- trunc 자릿수 “문자열” : 문자열 앞에서부터 자릿수까지만 남기고 제거
- “문자열” | replace “대상문자” “바꿀문자” : 문자열에서 대상문자를 바꿀문자로 바꿈
- contains “대상문자열” “문자열” : 문자열에서 대상문자열을 포함하는지 반환
- b64enc “문자열” : base 64로 인코딩

```yaml
trunc: {{ trunc 5 "hello world" }}
replace: {{ "hello world" | replace " " "-" }}
contains: {{ contains "cat" "catch" }}
b64enc: {{ b64enc "hello" }}
```

# 지역 변수 사용

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/8c8fb7a3-3a04-411c-b21a-45eb5e310c95)

- 템플릿 파일 안에서만 사용할 수 있는 지역 변수를 선언하고 사용할 수 있다.
- 선언 : `{{- $변수명 := 값 }}`
- 사용 : `{{ $변수명 }}`

```yaml
{{- $containerPort := 8080 }}

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  containers:
    - name: my-container
      image: my-image
      port: {{ $containerPort }}
```

with 내부에서 사용

- with 내부에서 사용되는 지역변수는 with에 설정된 스콥이 적용되지 않고 그대로 대치된다.

```yaml
data:
	dev:
	{{- $relname := .Release.Name -}}
	{{- with .Values.dev }}
		env: {{ .env }} # .Values.dev.env
		release: {{ $relName }} # .Release.Name
	{{- end }} 
```

range와 함께 사용

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/596ad613-e584-4b9e-9330-6e6568298c4e)

- 리스트의 인덱스를 함께 받을 때
- 맵의 key, value를 함께 받을 때

```yaml
index:
{{- range $index, $value := .Values.list }}
	{{ $index }}: {{ $value }}
{{- end }}

key-value:
{{- range $key, $value := .Values.map }}
	{{ $key }}: {{ $value | quote }}
{{- end }}
```

# 함수와 파이프라인 실습

[[내 차트 만들기2](https://kubetm.github.io/helm/02-template-guide/step_2/)](https://kubetm.github.io/helm/02-template-guide/step_2/)

차트 생성

```yaml
helm create mychart
```

불필요한 파일 삭제

```yaml
cd templates
rm -rf deployment.yaml hpa.yaml ingress.yaml serviceaccount.yaml service.yaml tests
```

## test-values.yaml에 속성 추가

```yaml
func:
  enabled: true
  
pipe:
  log: info
```

## Configmap에 함수와 파이프라인 사용하여 차트 작성

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: function-and-pipeline
data:
  Function_Argument:
    quote: {{ quote .Values.func.enabled }}     # quote(arg1)
    include: {{ include "mychart2.name" . }}  # include(arg1, arg2)

  Function_Quote:
    function_case1: {{ .Values.func.enabled }} # true
    function_case2: {{ quote .Values.func.enabled }} # "true"
    function_case3: "{{ .Values.func.enabled }}" # "true"

  Pipeline:
    upper: {{ .Values.pipe.log | upper }} # INFO
    upper.repeat: {{ .Values.pipe.log | upper | repeat 2 }} # INFOINFO
    upper.repeat.quote: {{ .Values.pipe.log | upper | repeat 2 | quote }} # "INFOINFO"
```

## 템플릿 조회

차트 루트 디렉터리에서

```bash
helm template mychart2 ./ -f test-values.yaml
```

```yaml
---
# Source: mychart2/templates/cm1.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: function-and-pipeline
data:
  Function_Argument:
    quote: "true"     # quote(arg1)
    include: mychart2  # include(arg1, arg2)

  Function_Quote:
    function_case1: true
    function_case2: "true"
    function_case3: "true"

  Pipeline:
    upper: INFO
    upper.repeat: INFOINFO
    upper.repeat.quote: "INFOINFO"
```

# 흐름 제어 실습

## ****test-values.yaml****

내용 추가

```yaml
dev:
  env: dev
  log: info

qa:
  env: qa
  log: info
  
prod:
  env: prod
  log: 
  
data:
  - a
  - b
  - c
```

## IF

- If 문에서 False 인 조건들 :  `Number:0, String: "", List: **[]**, Object: **{}**, Boolean: false, Null`
- If 문에 쓰이는 함수들 : `and**(&&)**, or**(||)**, ne**(**!**=)**, not**(**!**)**, eq**(=)**, ge**(**>**=)**, gt**(**>**)**, le**(**<**=)**, lt**(**<**)**, default, empty`

vi cm2-2.yaml

- {{ }} 안에 하이픈 없으면 줄바뀜 생김!
- 그래서 prod.env 다음에 공백

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-if
data:
  dev:
    env: {{ .Values.dev.env }}
    {{- if eq .Values.dev.env "dev" }} # "dev"이면
    log: debug                         # log는 debug
    {{- else if .Values.dev.log }} # log가 ""가 아니라면
    log: {{ .Values.dev.log }}     # 그 값을 사용
    {{- else }}
    log: error
    {{ end }}

  qa:
    env: {{ .Values.qa.env }}
    {{- if eq .Values.qa.env "dev" }}
    log: debug
    {{- else if .Values.qa.log }}
    log: {{ .Values.qa.log }}
    {{- else }}
    log: error
    {{- end }}

  prod:
    env: {{ .Values.prod.env }}
    {{ if eq .Values.prod.env "dev" }}
    log: debug
    {{ else if .Values.prod.log }}
    log: {{ .Values.prod.log }}
    {{ else }}
    log: error
    {{ end }}
```

템플릿 조회

```yaml
# Source: mychart2/templates/cm2-2.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-if
data:
  dev:
    env: dev
    log: debug                      

  qa:
    env: qa
    log: info

  prod:
    env: prod

    log: error
```

## WITH

vi cm2-3.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-with
data:
  dev:
  {{- with .Values.dev }}
    env: {{ .env }} # .Values.dev.env
    log: {{ .log }} # .Values.dev.log
  {{- end }}

  qa:
  {{- with .Values.qa }}
    env: {{ .env }} # .Values.qa.env
    log: {{ .log }} # .Values.qa.log
  {{- end }}
  
  prod:
  {{- with .Values.prod }}
    env: {{ .env }} # .Values.prod.env
    log: {{ .log }} # .Values.prod.log
  {{- end }}
```

템플릿 조회

```yaml
# Source: mychart2/templates/cm2-3.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-with
data:
  dev:
    env: dev
    log: info

  qa:
    env: qa
    log: info

  prod:
    env: prod
    log:
```

## RANGE

vi cm2-4.yaml

- .Values.data는 리스트
- range 없이 리스트 삽입 : `{{- .Values.data | toYaml | nindent 2 }}`
- range 사용 시 파이프를 사용해 원소에 함수를 적용할 수 있다

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-range
data:
  yaml:
  {{- .Values.data | toYaml | nindent 2 }}

  range:
  {{- range .Values.data }}
  - {{ . }}
  {{- end }}

  range-quote:
  {{- range .Values.data }}
  - {{ . | quote }}
  {{- end }}

  range-upper-quote:
  {{- range .Values.data }}
  - {{ . | upper | quote }}
  {{- end }}
```

템플릿 조회

```yaml
# Source: mychart2/templates/cm2-4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-range
data:
  yaml:
  - a
  - b
  - c

  range:
  - a
  - b
  - c

  range-quote:
  - "a"
  - "b"
  - "c"

  range-upper-quote:
  - "A"
  - "B"
  - "C"
```

# 함수 실습

## ****test-values.yaml****

속성 추가

```yaml
print:
  a: "1"
  b: "2"

ternary: 
  case1: true
  case2: false
  
default:
  nil: 
  list: []
  object: {}
  number: 0
  string: ""
  boolean: false
```

## ****configmap****

vi cm3.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: string-func
data:
  print:
    print:  {{ **print** "Hard Cording" }}
    printf: {{ **printf** "%s-%s" .Values.print.a .Values.print.b }}

  ternary:
    case1: {{ .Values.ternary.case1 | **ternary** "1" "2" }}
    case2: {{ .Values.ternary.case2 | **ternary** "1" "2" }}

  indent:
    indent: 
{{ .Values.data | toYaml | **indent** 4 }}
    nindent1: {{ .Values.data | toYaml | **nindent** 4 }}
    nindent2: # 이렇게 사용
    {{- .Values.data | toYaml | **nindent** 4 }}
          
  default: # Number:0, String: "", List: [], Object: {}, Boolean: false, Null
    nil:     {{ .Values.default.nil     | **default** "default" }}
    list:    {{ .Values.default.list    | default (list "default1" "default2") | toYaml | nindent 6}}
    object:  {{ .Values.default.object  | default "default:1" | toYaml | nindent 6 }}
    number:  {{ .Values.default.number  | default 1 }}
    string:  {{ .Values.default.string  | default "default" }}
    boolean: {{ .Values.default.boolean | default true }}

  trim:
    trim:       {{ **trim** "  hello " }}
    trimPrefix: {{ **trimPrefix** "-" "-hello" }}
    trimSuffix: {{ **trimSuffix** "-" "hello-" }}

  random:
    randAlphaNum: {{ **randAlphaNum** 5 }}   # 0-9a-zA-Z
    randAlpha:    {{ **randAlpha** 5 }}      # a-zA-Z
    randNumeric:  {{ **randNumeric** 5 }}    # 0-9
    randAscii:    {{ **randAscii** 5 }}      # ASCII characters

  trunc:    {{ **trunc** 5 "hello world" }}
  replace:  {{ "hello world" | **replace** " " "-" }}
  contains: {{ **contains** "cat" "catch" }}
  b64enc:   {{ **b64enc** "hello" }}
```

템플릿 조회

```yaml
# Source: mychart2/templates/cm3.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: string-func
data:
  print:
    print:  Hard Cording
    printf: 1-2

  ternary:
    case1: 1
    case2: 2

  indent:
    indent:
    - a
    - b
    - c
    nindent1:
    - a
    - b
    - c
    nindent2: # 이렇게 사용
    - a
    - b
    - c

  default: # Number:0, String: "", List: [], Object: {}, Boolean: false, Null
    nil:     default
    list:
      - default1
      - default2
    object:
      default:1
    number:  1
    string:  default
    boolean: true

  trim:
    trim:       hello
    trimPrefix: hello
    trimSuffix: hello

  random:
    randAlphaNum: dJOIy   # 0-9a-zA-Z
    randAlpha:    LGzaz      # a-zA-Z
    randNumeric:  63843    # 0-9
    randAscii:    FLx'F      # ASCII characters

  trunc:    hello
  replace:  hello-world
  contains: true
  b64enc:   aGVsbG8=
```

# 지역변수 실습

## WITH

- scope 무시

vi cm4-1.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-with
data:
  dev:
  {{- $relname := .Release.Name -}}
  {{- with .Values.dev }}
    env: {{ .env }}
    release: {{ $relname }}
    log: {{ .log }}
  {{- end }}
```

템플릿 조회

```yaml
# Source: mychart2/templates/cm4-1.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-with
data:
  dev:
    env: dev
    release: mychart2
    log: info
```

## RANGE

- 리스트 : 인덱스, 값
- 맵 : 키, 값

vi cm4-2.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-range
data:
  # for (int i ; i=list.length ; i++) { printf "i : list[i]" };
  index:
  {{- range $index, $value := .Values.data }}
    {{ $index }}: {{ $value }}
  {{- end }}

  # for (Map<key, value> map : list) { printf "map.key() : map.value()" };
  key-value:
  {{- range $key, $value := .Values.dev }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
```

템플릿 조회

```yaml
# Source: mychart2/templates/cm4-2.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-range
data:
  # for (int i ; i=list.length ; i++) { printf "i : list[i]" };
  index:
    0: a
    1: b
    2: c

  # for (Map<key, value> map : list) { printf "map.key() : map.value()" };
  key-value:
    env: "dev"
    log: "info"
```
