### ISSUE TITLE
Tomcat 분석하기

### ISSUE THREAD

**Issue by Mingadinga** [Mingadinga/2023_Study_Helm#7]
톰캣이 helm 차트를 어떻게 구성했는지 분석해보자. 어떤 함수가 어떤 패턴으로 어느 위치에서 사용되는지 익혀보자.

# 추가 함수

## dict

- dict 생성
- value 타입 상관 x
- 선언 : `dict 짝수개의 매개변수*`
- 조회 : `get 딕셔너리 “key”`

```yaml
{{- &myDict := dict "key1" "value1" }}
dict: {{ get $myDict "key1" }}
```

## include

- _helper.tpl에 변수를 선언하고, include 쪽에서 dict를 넘겨 사용할 수 있다.
- `include “변수명” (dict “키” “값”)`

```yaml
include “mychart.include” (dict “key1” “value1”) 

# helper.tpl
{{- define "mychart.include" -}}
key: {{ .key1 }} # value1
dict: {{ get . "key1" }} # value1
{{- end }}
```

## typeIs

- 타입 비교 연산
- `typeIs “타입” 값`
- 타입 타이포 주의

```yaml
{{- if typeIs "string" .Values.typels1 }}
typeIs: {{ Values.typel1 }}
{{- end }}

{{- if typeIs "bool" .Values.typels2 }}
typeIs: {{ Values.typel2 }}
{{- end }}
```

## tpl

- 템플릿 내의 템플릿으로 문자열을 인식
- 템플릿 문자열을 값으로 차트에 전달하거나 외부 구성 파일을 렌더링하는 데 유용
- `{{ tpl TEMPLATE_STRING VALUES }}`

```yaml
# data
defaultLevel: info
dev:
	env: dev
	log: "{{ .Values.defaultLevel }}"

normal: "{{ .Values.dev.log }}" # {{ .Values.defaultLevel }} "
tpl: "{{ tpl .Values.dev.log . }}" # info
```

## coalesce

- `coalesce 매개변수*` : 매개변수들 중 최초로 null이 아닌 값을 반환

```yaml
coalesce1: {{ coalesce .Values.data1 .Values.data2 "text1" }}
```

# Tomcat Helm으로 설치

- bitnami 레포 등록: `helm repo add bitnami https://charts.bitnami.com/bitnami`
- Tomcat 차트 다운 : `helm pull bitnami/tomcat --version 10.5.17`
- 압축해제 : `tar -xf tomcat-10.5.17.tgz`

아티팩트 허브에서 value 정보를 확인할 수 있다.

[[tomcat 10.9.3 · bitnami/bitnami](https://artifacthub.io/packages/helm/bitnami/tomcat)](https://artifacthub.io/packages/helm/bitnami/tomcat)

영상에서 실습한 톰캣 버전은 더이상 지원하지 않아서 최신 버전을 받았는데, 템플릿이 많이 달라짐. 그래서 영상에서 본 것 중에 처음 보거나 기억에 남는 것만 기록함.

# _helpers.tpl

전체
![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/3bd45df6-8d12-4219-9c29-574a729cd967)

**fullName - 조건문**

- .Values.fullnameOverride: null
- .Values.nameOverride: null
- .Chart.Name: tomcat
- .Release.Name: mytomcat

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/868e7dab-7e38-48da-ad77-ac473bc72ebb)

- 결과: tomcat.fullname: mytomcat

labels - 자신에서 include

- _helpers.tpl 안에서 _helpers.tpl의 지역 변수를 include 가능
- 먼저 선언되어야함
![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/580cb627-ba55-4b5e-bea7-d74cd34272cd)

# deployment.yaml

labels - 리스트로 가져오기

- 리스트 개별 원소에 함수 적용 가능

```yaml
# deployment.yaml
labels: {{- include "tomcat.labels" . | nindent 4 }}

# _helpers.tpl
labels:
	app: tomcat
	chart: tomcat-7.1.2
	release: mytomcat
	heritage: Helm

# 결과
labels:
	app: tomcat
	chart: tomcat-7.1.2
	release: mytomcat
	heritage: Helm
```

nodeSelector - include dict

```yaml
# values.yaml
nodeSelector: 
	group: a-zone

# deployment.yaml
nodeSelector: {{- include "tomcat.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}

# _helpers.tpl
# .value: group: a-zone
# .context: $
{{- define "tomcat.tplValue" -}}
	{{- if typeIs "string" .value }}
		{{- tpl .value .context }}
	{{ else }}
		{{- tpl (.value | toYaml) .context }}
	{{- end -}}
{{- end -}}
```

- 사실 결과만 보면 {{- toYaml .Values.nodeSelector | nindent 8 }}로 간단하게 사용해도 되지만
- 사용자가 nodeSelector을 “변수”로 사용하는 경우를 대비해 처리함
