### ISSUE TITLE
Prometheus 차트 분석하기

### ISSUE THREAD

**Issue by Mingadinga** [Mingadinga/2023_Study_Helm#8]
[[Prometheus 차트 분석](https://kubetm.github.io/helm/03-chart-analysis/prometheus/)](https://kubetm.github.io/helm/03-chart-analysis/prometheus/)

# 차트 다운

```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm pull prometheus-community/prometheus --version 13.8.0
tar -xf prometheus-13.8.0.tgz
```

# 차트 폴더 구조

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/43410381-c28a-4985-8037-89dff6451a80)

프로메테우스 헬름 파트는 모듈별로 폴더를 분리하여 별도의 차트를 제공한다. 사용자는 원하는 모듈을 선택하여 설치할 수 있다. 또 모듈 안에서 설치하고 싶지 않은 컴포넌트 설정을 통해 제외할 수 있다.

- node-exporter: 호스트 머신의 하드웨어 및 운영 체제 수준에서 메트릭 정보를 수집하는 데 사용. CPU, 메모리, 디스크, 네트워크 등
- alertmanager: 프로메테우스에서 발생하는 알림을 관리하고 경고를 전송하는 데 사용. 알림 규칙을 설정하고, 경고를 그룹화하고, 통합된 알림 메시지를 전송하고, 경고의 생명주기를 관리하는 등의 기능을 제공
- pushgateway: 주기적으로 업데이트되는 샘플 메트릭을 프로메테우스로 푸시하는 데 사용. 프로메테우스의 Pull 모델 대신 샘플 메트릭을 Push하는 방식으로 메트릭을 수집할 수 있다.
- server: 프로메테우스 서버 구성

# 종속성 관리

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/ce4c9219-0496-4468-b925-d5a5bd2bd05c)
프로메테우스 헬름 차트는 Kube-state-metrics 차트를 종속적으로 포함한다. 그 이유는 Prometheus가 Kubernetes 클러스터의 상태 및 메트릭 정보를 수집하기 위해 Kube-state-metrics를 사용하기 때문이다. 

Prometheus는 수집된 메트릭 데이터를 저장하고 이를 기반으로 모니터링, 경고 및 시각화를 수행하는 시스템이다. Kube-state-metrics는 Prometheus의 데이터 소스로 사용되며, Prometheus는 Kube-state-metrics가 수집한 메트릭을 쿼리하고 이를 기반으로 알림을 설정하거나 대시보드를 생성할 수 있다.

# 새로 배우는 함수

## split

splitList

- split해서 문자열 반환 : `splitList “구분자” “문자열”`
- split해서 객체 반환 : `split “구분자” “문자열”`
- 합치기 : `join “구분자” 리스트`
- 첫번째 : `first 리스트`
- 마지막 : `last 리스트`
- 첫번째 제외 나머지 : `rest 리스트`

```yaml
{{- $url := splitList "/" "helm.sh/docs/helm" }}
host: {{ first $url }} # "helm.sh"
path: {{ rest $url | join "/"}} # docs/helm
```

## regexMatch

- 문자열이 정규표현식을 따르는지 여부 반환 : `regexMatch “정규표현식” “문자열”`

```yaml
regexMatch: { regexMatch ".*.ya?ml$" "config.yaml" }}
```

## index

- 리스트 인덱스 조회 : `index 리스트 숫자`
- 탐색 조회 : `index 스코프객체 “key”*`

```yaml
colors: "{{ index .Values.colors 0 }}"
path: /{{ index .Values "server" "path" "prefix" }}/ready
```

## semver

- 버전 정보를 담은 객체 생성 : `semver “버전 정보”`
- 버전 비교 : `semverCompare “비교식” “비교대상버전”`

```yaml
{{- $version := "1.2.3-alpha.1+123" -}}
greaterthan: {{ semverCompare “>1.2.1” “1.2.3” }}
lessthen: {{ semverCompare "<1.2.1" "2.2.3"
equal: {{ semverCompare "=1.2.*" "1.2.3" }} # 1.2.0 <= [1.2.*] < 1.3.0
tilde: {{ semverCompare "~1.2.3" "1.2.0" # 1.2.3 <= [~1.2.3] < 1.3.0
```

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/18e941ba-e17c-4f9a-a4e1-e6c60ac97c80)

# Chart.yaml

종속 패키지

```yaml
dependencies:
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://kubernetes.github.io/kube-state-metrics
  version: 2.13.*
```

- condition true이면 name으로 된 종속성 함께 배포
- 종속 패키지를 같은 형식으로 추가 가능
- 데이터는 values.yaml에서 불러옴
- version 표현식 만족하는 가장 최신 버전의 차트를 가져옴. 종속성 설치하고 나면 Chart.lock 파일 생김
- 종속성 관리 명령어 : `helm dependency list`

# alertmanager 모듈의 cm.yaml

컴포넌트 선택 조건 - 전체 if

- 해당 조건에 맞지 않으면 컴포넌트 생성 안함
- .Values.alertmanager.enabled이 true이고
- .Values.alertmanager.configMapOverrideName과 .Values.alertmanager.configFromSecret가 emtpy

```yaml
{{- if and .Values.alertmanager.enabled (and (empty .Values.alertmanager.configMapOverrideName) (empty .Values.alertmanager.configFromSecret)) -}}
## ...
{{- end -}}
```

yml 파일 복사

```yaml
{{- range $key, $value := .Values.alertmanagerFiles }}
  {{- if $key | regexMatch ".*\\.ya?ml$" }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
  {{- else }}
  {{ $key }}: {{ toYaml $value | indent 4 }}
  {{- end }}
{{- end -}}
```

- key가 yaml 파일 이름이면 value를 yaml 형식으로 작성하고 복사(|)
- 아니라면 value를 yaml 형식으로 작성
    
![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/55bc9479-dcc6-4449-9a11-b69052963f4c)

# alertmanager 모듈의 ingress.yaml

컴포넌트 선택 조건 - 전체 if

```yaml
{{- if and .Values.alertmanager.enabled .Values.alertmanager.ingress.enabled -}}
# ..
{{- end -}}
```

- 해당 조건에 맞지 않으면 생성 안함
- .Values.alertmanager.enabled가 true이고 .Values.alertmanager.ingress.enabled도 true

spec .Capabilities

```yaml
spec:
  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
```

- .Capabilities : 배포된 쿠버네티스 정보를 담는 객체
- 실제 배포될 쿠버네티스 클러스터가 이러한 API를 가지고 있는지 확인

spec rules

```yaml
  rules:
  {{- range .Values.alertmanager.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
{{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
```

- item이 `alertmanager.domain.com` : url이 `alertmanager.domain.com`이고, path가 `/`
- item이 `domain.com/alertmanager` : url이 `[domain.com, alermanager]`이고, path가 `/alertmanager`

# server 모듈의 sts.yaml

컴포넌트 선택 조건 - 전체 if

```yaml
{{- if .Values.server.enabled -}}
{{- if .Values.server.statefulSet.enabled -}}
# ..
{{- end }}
{{- end }}
```

- 해당 조건에 맞지 않으면 생성 안함
- .Values.server.enabled가 true이고 ..Values.server.statefulSet.enabled도 true

쿠버네티스 버전 비교

```yaml
{{- if semverCompare ">=1.13-0" .Capabilities.KubeVersion.GitVersion }}
      {{- if or (.Values.server.enableServiceLinks) (eq (.Values.server.enableServiceLinks | toString) "<nil>") }}
      enableServiceLinks: true
      {{- else }}
      enableServiceLinks: false
      {{- end }}
{{- end }}
```

- 쿠버네티스 깃버전이 1.13-0 이상이고
- .Values.server.enableServiceLinks가 true이거나
- .Values.server.enableServiceLinks가 null이라면
- enableServiceLinks는 true, 둘다 아니라면 false
