### ISSUE TITLE
차트 개발 팁

### ISSUE THREAD

**Issue by Mingadinga** [Mingadinga/2023_Study_Helm#9]
[[차트 개발 팁과 요령](https://kubetm.github.io/helm/04-topic/tip/)](https://kubetm.github.io/helm/04-topic/tip/)

# 세팅

```bash
helm create mychart-tip
```

# install과 upgrade 구분

차트를 처음 배포할 땐 install, 파일 수정 후 배포할 때는 upgrade 명령어를 사용한다. 이 둘을 구분하기 위해 helm list로 특정 파드의 유무로 분기하는 로직을 작성해야하는데, 이는 다소 불편하다. 한번에 해주는 명령어를 알아보자.

- helm install create namespace 옵션 : helm install 시 파드를 배포할 ns를 선택하고, ns가 없으면 생성한다. `helm install mychart -n nm-1 --create-namespace`
- helm upgrade install 옵션 : 파드의 최초 배포 여부 상관없이 사용할 수 있는 명령어. install 옵션을 주면 해당 파드가 배포되어있지 않다면 파드를 배포한다. `helm upgrade mychart -n nm-1 --create-namespace --install`

vi deployment.yaml

- 파드 배포 후 30초 sleep

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      type: app
  replicas: 1
  template:
    metadata:
      labels:
        type: app
    spec:
      initContainers:
      - name: init-myservice
        image: kubetm/app
        command: ["sh", "-c", "echo 'start'; sleep 30; echo 'done'"]
      containers:
      - name: container
        image: kubetm/app
        envFrom:
        - configMapRef:
            name: test-cm
        volumeMounts:
        - name: volume
          mountPath: /hostpath
      volumes:
      - name : volume
        persistentVolumeClaim:
          claimName: test-pvc
```

명령 실습

```bash
helm install mychart-tip . -n nm-1
# Error: INSTALLATION FAILED: create: failed to create: namespaces "nm-1" not found

helm install mychart-tip . -n nm-1 --create-namespace # revision: 1
kubectl get ns nm-1
kubectl get -n nm-1 pods

helm upgrade mychart-tip . -n nm-1 # revision: 2
helm uninstall mychart -n nm-1

helm upgrade mychart-tip . -n nm-1 --create-namespace --install
```

# helm install pod 상태 확인 후 결과 리턴

install 후 pod 상태에 상관없이 deployed를 리턴한다. 만약 pod가 running인 것까지 확인하고 싶다면 wait 옵션을 사용한다. 디폴트 타임아웃을 5분으로 잡는데, 더 늘릴 수 있다.

`helm upgrade mychart -n nm-1 --create-namespace --install --wait --timeout 10m`

```bash
helm upgrade mychart-tip . -n nm-1 --create-namespace --install
helm upgrade mychart-tip . -n nm-1 --create-namespace --install --wait --timeout 10s
# --wait : 30초 동안 기다림
```

# Configmap 변경 시 자동으로 Pod에 적용

configmap.yaml 파일을 수정하고 helm으로 배포하면 쿠버네티스의 cm에 반영되지만 이 정보를 Pod가 갖다 쓰지는 않는다. 그래서 pod를 재기동해야하는데, Configmap 변경 시 Pod가 이를 감지하여 다시 파드를 재기동할 수 있도록 deployment.yaml에 로직을 추가한다.

```yaml
annotations:
  checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

컨피그맵 파일 내용을 암호화해서 checksum/config 내용으로 넣는다. 컨피그맵 파일에 변경사항이 생기면 값이 변하므로 deployment 입장에서 업데이트 항목이 있는 것으로 간주하고 파드를 재생성한다. 재생성되는 파드는 변경된 컨피그맵을 사용한다.

vi configmap.yaml - cm은 바뀌지만 파드는 모른다

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  env: prod
  log: Info # 수정
```

vi deployment.yaml - configmap의 변화 감지

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      type: app
  replicas: 1
  template:
    metadata:
      labels:
        type: app
			# 추가
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
#        rollme: {{ randAlphaNum 5 | quote }}
```

```bash
helm upgrade mychart-tip . -n nm-1 --create-namespace --install
kubectl get -n nm-1 pods
kubectl exec -n nm-1 test-5957b58d99-kgdfh -it env

helm upgrade mychart-tip . -n nm-1 --create-namespace --install
kubectl get -n nm-1 pods
kubectl get -n nm-1 deployment -o yaml
```

# 랜덤함수를 사용하여 항상 파드 재배포

컨피그맵의 변경사항과 상관없이 항상 파드를 재배포할 수 있다. 

```yaml
annotations:
# checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  rollme: {{ randAlphaNum 5 | quote }}
```

랜덤 다섯자리 문자열을 생성한다. 배포할 때마다 값이 바뀌므로, 디플로이먼트 내용이 변경됐다고 판단하여 항상 파드가 재생성된다.

보통 개발 환경에서는 latest 이미지를 사용하는데, 그러면 소스는 변경되어도 컨테이너 이미지의 이름이 같아서 디플로이먼트에 변경사항이 없는걸로 판단, 자동으로 배포되지 않는다. 위의 랜덤 함수를 사용하면 항상 재배포된다.

주의사항은 비번으로 랜덤 함수를 사용하는 경우에 내용이 바뀌지 않아도 항상 재배포된다는 점이다. 제어 로직을 사용하거나 헬름 훅을 사용하여 제어해야한다.

# PV 변경 시 적용 방법

파드의 yaml을 변경하고 배포하면 바로 오류가 난다. 그 이유는 PV가 파드와 바운딩되어 Bound 상태일 경우 수정이 불가능하기 때문이다. PV uninstall 후 다시 install 해야 한다.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1G
  hostPath:
    path: /host2 # 수정
    type: DirectoryOrCreate
```

```bash
helm upgrade mychart-tip . -n nm-1 --create-namespace --install
# UPGRADE FAILED: cannot patch "test-pv" with kind PersistentVolum

# uninstall
helm uninstall mychart-tip -n nm-1
kubectl get pv # 지워진 것 확인
kubectl get pvc -n nm-1 # 지워진 것 확인

# 다시 install
helm upgrade mychart-tip . -n nm-1 --create-namespace --install
kubectl get pv -o yaml

helm list -n nm-1
helm uninstall mychart-tip -n nm-1
helm list -n nm-1 # 릴리즈 삭제
kubectl get ns nm-1 # ns는 삭제되지 않음
kubectl delete ns nm-1
```

# Helm uninstall 시 Namespace 삭제

helm uninstall을 하더라도 Namespace는 삭제되지 않고, 차트로 생성한 리소스만 삭제한다. 그 이유는 네임 스페이스 안에 여러 차트로 배포한 리소스들이 있을 수 있기 때문이다. uninstall 한다고 네임 스페이스 자체를 삭제해버리면 다른 차트를 통해 네임스페이스에 배포된 리소스들까지 함께 삭제된다.

헬름을 사용하더라도 쿠버네티스 리소스의 고유 기능을 잘 생각해봐야한다.

# Helm의 데이터 저장소

배포나 업그레이드에 대한 정보는 모두 Namespace의 Secret에 저장된다. 배포를 할때마다 Secret이 추가되며, 이 Secret에 name과 릴리즈 정보가 암호화되어 들어간다. helm history 명령어를 사용하면 배포 이력을 확인할 수 있다. helm upgrade로 history-max 옵션으로 남길 최신 시크릿 개수를 지정할 수 있다. 

```bash
helm upgrade mychart-tip . -n nm-1 --create-namespace --install

# 시크릿 확인
kubectl get -n nm-1 secret -l name=mychart-tip
kubectl get -n nm-1 secret sh.helm.release.v1.mychart.v1 -o yaml

# 히스토리 확인
helm history -n nm-1 mychart-tip
helm upgrade mychart-tip . -n nm-1 --create-namespace --install --history-max 2
kubectl get -n nm-1 secret -l name=mychart-tip
helm history -n nm-1 mychart-tip
```

![image](https://github.com/Mingadinga/2023_Study_Helm/assets/53958188/f0bb8d03-9edd-4d4f-8a11-ef5724e8b70a)
